[build]
  command = "npm run build"
  publish = "public/"
  environment = { NODE_VERSION = "14", NPM_VERSION = "8.1.3" }

# [context.production]
# [context.deploy-preview]
# [context.branch-deploy]

# [[redirects]]

[[plugins]]
  package = "@netlify/plugin-gatsby"